2023-12-27 18:54:53,242 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2023-12-27 18:54:53,439 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2023-12-27 18:54:59,360 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345836 is handled. Duration 271 ms by bot id=6638457850
2023-12-27 18:55:00,529 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345837 is handled. Duration 123 ms by bot id=6638457850
2023-12-27 18:55:05,384 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345838 is handled. Duration 180 ms by bot id=6638457850
2023-12-27 18:55:08,003 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345839 is handled. Duration 138 ms by bot id=6638457850
2023-12-27 18:55:22,446 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345840 is handled. Duration 138 ms by bot id=6638457850
2023-12-27 18:55:32,591 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345841 is handled. Duration 307 ms by bot id=6638457850
2023-12-27 18:55:47,021 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345842 is handled. Duration 185 ms by bot id=6638457850
2023-12-27 18:55:49,327 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345843 is handled. Duration 168 ms by bot id=6638457850
2023-12-27 18:55:52,760 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345844 is handled. Duration 359 ms by bot id=6638457850
2023-12-27 18:56:04,303 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2023-12-27 18:56:05,421 - [ERROR] - root - (admin_handlers.py).accept_image(123) - An error occurred (404) when calling the HeadObject operation: Not Found
2023-12-27 18:56:05,886 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345845 is handled. Duration 2205 ms by bot id=6638457850
2023-12-27 18:56:27,371 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345846 is handled. Duration 223 ms by bot id=6638457850
2023-12-27 18:56:31,392 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345847 is handled. Duration 244 ms by bot id=6638457850
2023-12-27 18:56:38,468 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345848 is handled. Duration 154 ms by bot id=6638457850
2023-12-27 18:56:46,437 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345849 is handled. Duration 2209 ms by bot id=6638457850
2023-12-27 18:57:04,112 - [ERROR] - root - (admin_handlers.py).moderate_image(83) - 'NoneType' object has no attribute 'id'
2023-12-27 18:57:04,323 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345850 is handled. Duration 231 ms by bot id=6638457850
2023-12-27 19:40:08,469 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 19:40:08,492 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 19:40:19,763 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 20:16:12,316 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345851 is handled. Duration 248 ms by bot id=6638457850
2023-12-27 21:29:09,757 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 21:29:09,759 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 21:29:21,047 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 21:55:04,907 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 21:55:04,909 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 21:55:16,133 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 22:10:55,359 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 22:10:55,361 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 22:11:06,619 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 22:31:02,866 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 22:31:02,868 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 22:31:14,058 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 22:48:59,416 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 22:48:59,418 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 22:49:10,715 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 23:09:21,710 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 23:09:21,712 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 23:09:32,925 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 23:29:13,216 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 23:29:13,217 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 23:29:24,452 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-27 23:48:28,140 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-27 23:48:28,142 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-27 23:48:39,454 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 00:54:35,662 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 00:54:35,681 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 00:54:46,976 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 01:14:53,293 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 01:14:53,295 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 01:15:04,595 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 01:35:55,746 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 01:35:55,747 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 01:36:07,050 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 01:53:58,200 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 01:53:58,204 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 01:54:09,516 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 02:16:18,620 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 02:16:18,621 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 02:16:30,764 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 02:35:56,703 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 02:35:56,705 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 02:36:07,904 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 02:55:54,455 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 02:55:54,456 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 02:56:05,670 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 03:16:29,621 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 03:16:29,623 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 03:16:41,051 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 03:36:28,672 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 03:36:28,674 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 03:36:39,877 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 03:56:44,402 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 03:56:44,403 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 03:56:55,669 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 04:14:44,525 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 04:14:44,528 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 04:14:55,772 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 04:38:25,767 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 04:38:25,768 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 04:38:36,995 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 04:59:06,134 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 04:59:06,137 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 04:59:17,376 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 05:18:38,781 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 05:18:38,783 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 05:18:50,094 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 05:38:16,854 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 05:38:16,856 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 05:38:28,072 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 06:01:22,925 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 06:01:22,927 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 06:01:34,229 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 06:19:19,425 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 06:19:19,426 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 06:19:30,738 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 06:38:33,784 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 06:38:33,786 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 06:38:45,082 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 06:56:47,051 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 06:56:47,053 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 06:56:58,271 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 07:15:16,731 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 07:15:16,732 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 07:15:27,962 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 07:31:16,548 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 07:31:16,549 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 07:31:27,774 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 07:52:53,642 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 07:52:53,644 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 07:53:04,832 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 08:11:25,540 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 08:11:25,542 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 08:11:36,773 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 08:42:42,303 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 08:42:42,305 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 08:42:53,588 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 09:05:09,005 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 09:05:09,006 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 09:05:20,211 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 09:22:19,030 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 09:22:19,033 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 09:22:20,243 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 09:22:20,613 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345852 is handled. Duration 365 ms by bot id=6638457850
2023-12-28 09:23:42,021 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345853 is handled. Duration 250 ms by bot id=6638457850
2023-12-28 09:23:48,897 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345854 is handled. Duration 163 ms by bot id=6638457850
2023-12-28 09:29:01,868 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2023-12-28 09:29:01,893 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2023-12-28 09:29:01,908 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2023-12-28 09:29:08,974 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2023-12-28 09:29:09,190 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2023-12-28 09:29:36,339 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345855 is handled. Duration 290 ms by bot id=6638457850
2023-12-28 09:38:36,019 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345856 is handled. Duration 540 ms by bot id=6638457850
2023-12-28 09:55:58,392 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 09:55:58,400 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 09:56:57,750 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientConnectorError: Cannot connect to host api.telegram.org:443 ssl:default [Connection reset by peer]
2023-12-28 09:56:57,751 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.184260 seconds and try again... (tryings = 1, bot id = 6638457850)
2023-12-28 09:57:09,166 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 2, bot id = 6638457850)
2023-12-28 10:48:10,860 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 10:48:10,862 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 10:48:22,074 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 11:45:04,596 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2023-12-28 11:45:04,666 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2023-12-28 11:45:04,672 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2023-12-28 11:45:11,830 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2023-12-28 11:45:12,528 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2023-12-28 11:45:18,918 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345857 is handled. Duration 236 ms by bot id=6638457850
2023-12-28 11:45:19,999 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345858 is handled. Duration 105 ms by bot id=6638457850
2023-12-28 11:45:35,628 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2023-12-28 11:45:36,847 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345859 is handled. Duration 1393 ms by bot id=6638457850
2023-12-28 13:44:35,523 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 13:44:35,535 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 13:44:47,200 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 14:34:40,759 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 14:34:40,769 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 14:34:52,063 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 16:40:41,706 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 16:40:41,710 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 16:40:52,942 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-28 18:56:48,588 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 18:56:48,589 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 19:57:52,304 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 19:57:52,307 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.298821 seconds and try again... (tryings = 1, bot id = 6638457850)
2023-12-28 20:49:42,470 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 20:49:42,470 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.656145 seconds and try again... (tryings = 2, bot id = 6638457850)
2023-12-28 20:56:16,685 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 3, bot id = 6638457850)
2023-12-28 22:45:13,993 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-28 22:45:13,995 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-28 22:45:25,242 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-29 02:04:17,386 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-29 02:04:17,394 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-29 03:05:37,766 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-29 03:05:37,779 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.250530 seconds and try again... (tryings = 1, bot id = 6638457850)
2023-12-29 03:05:49,311 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 2, bot id = 6638457850)
2023-12-29 05:07:58,665 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-29 05:07:58,673 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-29 06:08:44,179 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-29 06:08:54,155 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 54] Connection reset by peer
2023-12-29 06:08:54,155 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-29 06:09:05,479 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2023-12-29 08:11:23,826 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-29 08:11:23,834 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2023-12-29 10:00:42,872 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-12-29 10:00:42,880 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.359910 seconds and try again... (tryings = 1, bot id = 6638457850)
2023-12-29 10:00:54,531 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 2, bot id = 6638457850)
2023-12-29 11:31:40,885 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2023-12-29 11:31:40,929 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2023-12-29 11:31:40,939 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2024-01-03 13:19:13,213 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-03 13:19:13,505 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-03 13:19:29,127 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345860 is handled. Duration 357 ms by bot id=6638457850
2024-01-03 13:19:30,168 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345861 is handled. Duration 152 ms by bot id=6638457850
2024-01-03 13:19:31,250 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345862 is handled. Duration 91 ms by bot id=6638457850
2024-01-03 13:19:32,747 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345863 is handled. Duration 197 ms by bot id=6638457850
2024-01-03 13:19:38,585 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345864 is handled. Duration 96 ms by bot id=6638457850
2024-01-03 13:19:39,754 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345865 is handled. Duration 121 ms by bot id=6638457850
2024-01-03 13:19:41,249 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345866 is handled. Duration 122 ms by bot id=6638457850
2024-01-03 13:19:43,841 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345867 is handled. Duration 103 ms by bot id=6638457850
2024-01-03 13:19:45,235 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345868 is handled. Duration 90 ms by bot id=6638457850
2024-01-03 13:19:46,800 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345869 is handled. Duration 299 ms by bot id=6638457850
2024-01-03 13:19:47,597 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345870 is handled. Duration 106 ms by bot id=6638457850
2024-01-03 13:19:54,448 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-01-03 13:19:56,144 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345871 is handled. Duration 1782 ms by bot id=6638457850
2024-01-03 15:54:25,535 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-03 15:54:25,568 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-03 15:54:36,871 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-03 16:19:28,963 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-03 16:19:28,967 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-03 16:19:40,341 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-03 17:19:35,233 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-03 17:19:35,236 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-03 17:34:03,590 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-03 18:37:18,658 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-03 18:37:18,674 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-03 18:37:29,886 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-03 19:22:45,072 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-03 19:22:45,079 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-03 19:22:56,556 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-04 00:40:34,735 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 00:40:34,764 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 02:35:40,878 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 02:35:40,886 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.314076 seconds and try again... (tryings = 1, bot id = 6638457850)
2024-01-04 03:36:11,352 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 2, bot id = 6638457850)
2024-01-04 03:36:11,767 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 54] Connection reset by peer
2024-01-04 03:36:11,768 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 03:36:23,463 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-04 05:38:49,590 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 05:38:49,599 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 05:39:01,246 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-04 07:43:53,487 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 07:43:53,496 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 07:44:04,746 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-04 09:41:55,194 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 09:41:55,235 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 09:42:06,773 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-04 10:38:26,630 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 10:38:26,635 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 10:38:37,860 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-04 13:42:48,949 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-04 13:42:48,967 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-04 13:43:00,487 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-08 15:59:19,180 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-08 15:59:19,408 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 15:59:29,622 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345872 is handled. Duration 425 ms by bot id=6638457850
2024-01-08 15:59:31,588 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345873 is handled. Duration 112 ms by bot id=6638457850
2024-01-08 15:59:47,046 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345874 is not handled. Duration 6 ms by bot id=6638457850
2024-01-08 15:59:47,047 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345874 by bot id=6638457850
AttributeError: 'State' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 83, in post_choosing_academic_year
    await UserPresenter.set_state(UserCallbackData.academic_year)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/user_presenter/user_presenter.py", line 32, in set_state
    await state.storage.set_state(key=state.key, state=new_state)
          ^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'storage'
2024-01-08 16:00:19,630 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2024-01-08 16:00:19,632 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 16:00:19,632 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2024-01-08 16:00:25,185 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-08 16:00:25,366 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 16:00:31,560 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345875 is handled. Duration 666 ms by bot id=6638457850
2024-01-08 16:00:32,782 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345876 is handled. Duration 98 ms by bot id=6638457850
2024-01-08 16:00:33,652 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345877 is not handled. Duration 115 ms by bot id=6638457850
2024-01-08 16:00:33,652 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345877 by bot id=6638457850
AttributeError: 'State' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 88, in post_choosing_academic_year
    await UserPresenter.set_state(UserCallbackData.academic_year)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/user_presenter/user_presenter.py", line 32, in set_state
    await state.storage.set_state(key=state.key, state=new_state)
          ^^^^^^^^^^^^^
AttributeError: 'State' object has no attribute 'storage'
2024-01-08 17:11:16,706 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-08 17:11:16,748 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-08 17:11:28,037 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-08 17:45:47,461 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2024-01-08 17:45:47,561 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 17:45:47,573 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2024-01-08 18:58:10,507 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-08 18:58:11,063 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 18:58:25,844 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345878 is handled. Duration 488 ms by bot id=6638457850
2024-01-08 18:58:27,912 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345879 is handled. Duration 362 ms by bot id=6638457850
2024-01-08 18:58:29,580 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345880 is not handled. Duration 41 ms by bot id=6638457850
2024-01-08 18:58:29,580 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345880 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 18:58:50,597 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345881 is handled. Duration 275 ms by bot id=6638457850
2024-01-08 18:58:53,606 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345882 is handled. Duration 195 ms by bot id=6638457850
2024-01-08 18:58:54,426 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345883 is not handled. Duration 6 ms by bot id=6638457850
2024-01-08 18:58:54,426 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345883 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 18:58:56,278 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345884 is handled. Duration 294 ms by bot id=6638457850
2024-01-08 18:58:58,633 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345885 is handled. Duration 121 ms by bot id=6638457850
2024-01-08 18:59:02,849 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345886 is handled. Duration 222 ms by bot id=6638457850
2024-01-08 18:59:04,106 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345887 is handled. Duration 256 ms by bot id=6638457850
2024-01-08 18:59:05,385 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345888 is not handled. Duration 224 ms by bot id=6638457850
2024-01-08 18:59:05,385 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345888 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:01:22,715 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2024-01-08 19:01:22,761 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 19:01:22,763 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2024-01-08 19:01:38,193 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-08 19:01:38,393 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 19:01:49,612 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345889 is handled. Duration 387 ms by bot id=6638457850
2024-01-08 19:01:52,414 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345890 is handled. Duration 220 ms by bot id=6638457850
2024-01-08 19:01:53,236 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345891 is not handled. Duration 5 ms by bot id=6638457850
2024-01-08 19:01:53,236 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345891 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:00,230 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345892 is not handled. Duration 1 ms by bot id=6638457850
2024-01-08 19:02:00,230 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345892 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:03,041 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345893 is handled. Duration 99 ms by bot id=6638457850
2024-01-08 19:02:04,514 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345894 is handled. Duration 109 ms by bot id=6638457850
2024-01-08 19:02:05,980 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345895 is not handled. Duration 19 ms by bot id=6638457850
2024-01-08 19:02:05,980 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345895 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:07,780 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345896 is not handled. Duration 1 ms by bot id=6638457850
2024-01-08 19:02:07,780 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345896 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:09,138 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345897 is not handled. Duration 869 ms by bot id=6638457850
2024-01-08 19:02:09,151 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345897 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:09,842 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345899 is not handled. Duration 611 ms by bot id=6638457850
2024-01-08 19:02:09,842 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345899 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:09,879 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345898 is not handled. Duration 972 ms by bot id=6638457850
2024-01-08 19:02:09,879 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345898 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:11,735 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345901 is not handled. Duration 335 ms by bot id=6638457850
2024-01-08 19:02:11,735 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345901 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:11,743 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345900 is not handled. Duration 681 ms by bot id=6638457850
2024-01-08 19:02:11,743 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345900 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:11,752 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345902 is not handled. Duration 3 ms by bot id=6638457850
2024-01-08 19:02:11,753 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345902 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:14,440 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345904 is not handled. Duration 586 ms by bot id=6638457850
2024-01-08 19:02:14,440 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345904 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:14,452 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345903 is not handled. Duration 2560 ms by bot id=6638457850
2024-01-08 19:02:14,452 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345903 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:16,690 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345905 is not handled. Duration 162 ms by bot id=6638457850
2024-01-08 19:02:16,692 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345905 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:02:58,225 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345906 is handled. Duration 224 ms by bot id=6638457850
2024-01-08 19:03:04,836 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345907 is handled. Duration 123 ms by bot id=6638457850
2024-01-08 19:03:07,481 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345908 is not handled. Duration 17 ms by bot id=6638457850
2024-01-08 19:03:07,481 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345908 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 84, in post_choosing_academic_year
    await presenter.get_fsm_storage.update_data(method=query.data.split(':')[1])
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:03:10,252 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345909 is handled. Duration 132 ms by bot id=6638457850
2024-01-08 19:03:17,600 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345910 is not handled. Duration 2 ms by bot id=6638457850
2024-01-08 19:03:17,600 - [ERROR] - aiogram.event - (dispatcher.py)._process_update(315) - Cause exception while process update id=849345910 by bot id=6638457850
AttributeError: 'NoneType' object has no attribute 'storage'
Traceback (most recent call last):
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/storage/memory.py", line 56, in lock
    yield
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 144, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/view/user_handlers/user_handlers.py", line 112, in get_choosing_academic_year
    await presenter.get_fsm_storage.update_data(
  File "/Users/timurhajrulin/Desktop/PetProjects/cheat_bot/cheat_bot/presenter/fsm_presenter/fsm_presenter.py", line 27, in update_data
    return await self.__state.storage.update_data(key=self.__state.key, data=kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'storage'
2024-01-08 19:05:58,880 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2024-01-08 19:05:58,972 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 19:05:58,974 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2024-01-08 19:06:09,895 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-08 19:06:10,141 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 19:06:20,156 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345911 is handled. Duration 500 ms by bot id=6638457850
2024-01-08 19:06:21,424 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345912 is handled. Duration 162 ms by bot id=6638457850
2024-01-08 19:06:23,140 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345913 is handled. Duration 196 ms by bot id=6638457850
2024-01-08 19:07:37,116 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._signal_stop_polling(455) - Received SIGINT signal
2024-01-08 19:07:37,163 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(359) - Polling stopped for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 19:07:37,174 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(554) - Polling stopped
2024-01-08 19:07:48,994 - [INFO] - aiogram.dispatcher - (dispatcher.py).start_polling(527) - Start polling
2024-01-08 19:07:49,199 - [INFO] - aiogram.dispatcher - (dispatcher.py)._polling(341) - Run polling for bot @stu_cheat_bot id=6638457850 - 'cheat_bot'
2024-01-08 19:07:52,150 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345914 is handled. Duration 481 ms by bot id=6638457850
2024-01-08 19:07:58,079 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345915 is handled. Duration 105 ms by bot id=6638457850
2024-01-08 19:08:03,890 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345916 is handled. Duration 133 ms by bot id=6638457850
2024-01-08 19:08:35,358 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345917 is handled. Duration 312 ms by bot id=6638457850
2024-01-08 19:08:45,665 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-01-08 19:08:47,892 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849345918 is handled. Duration 2680 ms by bot id=6638457850
2024-01-08 20:02:43,326 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-08 20:02:43,346 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-08 20:04:00,484 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-08 20:11:21,525 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-08 20:11:21,538 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-08 20:11:32,777 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-08 21:44:27,275 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-08 21:44:27,285 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-08 21:44:52,848 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-08 22:24:29,672 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-08 22:24:29,698 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-01-08 22:24:58,388 - [INFO] - aiogram.dispatcher - (dispatcher.py)._listen_updates(233) - Connection established (tryings = 1, bot id = 6638457850)
2024-01-09 00:14:15,881 - [ERROR] - aiogram.dispatcher - (dispatcher.py)._listen_updates(219) - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2024-01-09 00:14:16,173 - [WARNING] - aiogram.dispatcher - (dispatcher.py)._listen_updates(221) - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6638457850)
2024-02-03 11:06:29,828 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:06:29,892 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:18:05,001 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:18:05,110 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:20:45,051 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:20:45,147 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:23:09,078 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:23:09,135 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:25:38,332 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:25:38,422 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:30:44,271 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:30:44,367 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:33:08,466 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:33:08,581 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:38:59,068 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 11:38:59,167 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 17:06:15,683 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346042 is not handled. Duration 4 ms by bot id=6638457850
2024-02-03 17:06:23,997 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 17:06:24,012 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-03 17:06:24,013 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346034 is not handled. Duration 144 ms by bot id=6638457850
2024-02-14 14:11:24,909 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346112 is handled. Duration 365 ms by bot id=6638457850
2024-02-14 14:11:25,963 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346113 is handled. Duration 134 ms by bot id=6638457850
2024-02-14 14:11:27,707 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346114 is handled. Duration 138 ms by bot id=6638457850
2024-02-14 14:11:29,070 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346115 is handled. Duration 215 ms by bot id=6638457850
2024-02-14 14:11:33,352 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346116 is handled. Duration 150 ms by bot id=6638457850
2024-02-25 16:58:51,973 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:58:52,032 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:58:52,185 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346250 is handled. Duration 463 ms by bot id=6638457850
2024-02-25 16:58:54,143 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:58:54,191 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:58:54,191 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346251 is not handled. Duration 263 ms by bot id=6638457850
2024-02-25 16:58:56,393 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:58:56,443 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:58:56,444 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346251 is not handled. Duration 126 ms by bot id=6638457850
2024-02-25 16:59:00,540 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:59:00,587 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:59:00,588 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346251 is not handled. Duration 107 ms by bot id=6638457850
2024-02-25 16:59:08,729 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:59:08,778 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:59:08,779 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346251 is not handled. Duration 156 ms by bot id=6638457850
2024-02-25 16:59:24,893 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:59:24,941 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 16:59:24,942 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346251 is not handled. Duration 125 ms by bot id=6638457850
2024-02-25 17:00:54,430 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:00:54,486 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:00:54,758 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346253 is handled. Duration 569 ms by bot id=6638457850
2024-02-25 17:01:01,147 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:01,195 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:01,195 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346251 is not handled. Duration 151 ms by bot id=6638457850
2024-02-25 17:01:01,578 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:01,627 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:01,627 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346252 is not handled. Duration 248 ms by bot id=6638457850
2024-02-25 17:01:03,747 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:03,829 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:03,829 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346252 is not handled. Duration 154 ms by bot id=6638457850
2024-02-25 17:01:08,098 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:08,144 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:08,145 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346252 is not handled. Duration 132 ms by bot id=6638457850
2024-02-25 17:01:16,290 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:16,337 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:16,338 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346252 is not handled. Duration 155 ms by bot id=6638457850
2024-02-25 17:01:32,447 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:32,495 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:32,496 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346252 is not handled. Duration 119 ms by bot id=6638457850
2024-02-25 17:01:32,736 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:32,828 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:32,829 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346254 is not handled. Duration 286 ms by bot id=6638457850
2024-02-25 17:01:35,028 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:35,078 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:35,080 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346254 is not handled. Duration 191 ms by bot id=6638457850
2024-02-25 17:01:39,282 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:39,300 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:01:39,301 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346254 is not handled. Duration 137 ms by bot id=6638457850
2024-02-25 17:17:43,307 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:17:43,377 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:20:14,405 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:20:14,432 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:20:14,476 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:20:14,534 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:20:15,978 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:20:15,991 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:33:11,156 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:33:11,289 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:38:34,352 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:38:34,461 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:08,063 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:08,174 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:08,176 - [ERROR] - root - (admin_handlers.py).moderate_image(84) - 'asyncpg.Record' object has no attribute 'id'
2024-02-25 17:44:08,459 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346265 is handled. Duration 1096 ms by bot id=6638457850
2024-02-25 17:44:08,754 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:08,813 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:08,814 - [ERROR] - root - (admin_handlers.py).moderate_image(84) - 'asyncpg.Record' object has no attribute 'id'
2024-02-25 17:44:08,911 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346266 is handled. Duration 396 ms by bot id=6638457850
2024-02-25 17:44:09,161 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:09,216 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:09,217 - [ERROR] - root - (admin_handlers.py).moderate_image(84) - 'asyncpg.Record' object has no attribute 'id'
2024-02-25 17:44:09,339 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346267 is handled. Duration 394 ms by bot id=6638457850
2024-02-25 17:44:09,563 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:09,614 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:44:09,614 - [ERROR] - root - (admin_handlers.py).moderate_image(84) - 'asyncpg.Record' object has no attribute 'id'
2024-02-25 17:44:09,732 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346268 is handled. Duration 356 ms by bot id=6638457850
2024-02-25 17:48:00,917 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:48:01,069 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:48:01,071 - [ERROR] - root - (admin_handlers.py).moderate_image(84) - 'asyncpg.Record' object has no attribute 'id'
2024-02-25 17:48:01,333 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346269 is handled. Duration 1311 ms by bot id=6638457850
2024-02-25 17:49:25,561 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:49:25,768 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:49:26,068 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346270 is handled. Duration 1514 ms by bot id=6638457850
2024-02-25 17:50:32,369 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:50:32,516 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:54:04,125 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:54:04,181 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:55:36,273 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:55:36,338 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:55:36,480 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 17:55:36,532 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 18:55:39,664 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-02-25 18:56:10,296 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346310 is not handled. Duration 30924 ms by bot id=6638457850
2024-02-25 18:57:54,860 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-02-25 18:59:33,433 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-02-25 18:59:34,538 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346310 is not handled. Duration 1398 ms by bot id=6638457850
2024-02-25 21:09:37,074 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:09:37,428 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:09:37,429 - [ERROR] - root - (admin_handlers.py).moderate_image(84) - 'NoneType' object has no attribute 'id'
2024-02-25 21:09:38,116 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346352 is handled. Duration 2145 ms by bot id=6638457850
2024-02-25 21:09:59,480 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346353 is handled. Duration 306 ms by bot id=6638457850
2024-02-25 21:10:03,461 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346354 is handled. Duration 260 ms by bot id=6638457850
2024-02-25 21:10:05,778 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346355 is handled. Duration 572 ms by bot id=6638457850
2024-02-25 21:10:15,523 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346356 is handled. Duration 244 ms by bot id=6638457850
2024-02-25 21:10:23,737 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346357 is handled. Duration 345 ms by bot id=6638457850
2024-02-25 21:10:35,539 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:10:35,694 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:10:35,792 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346358 is handled. Duration 660 ms by bot id=6638457850
2024-02-25 21:10:43,444 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:10:43,588 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:10:44,077 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:10:44,143 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:10:44,325 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346359 is handled. Duration 1280 ms by bot id=6638457850
2024-02-25 21:10:46,771 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-02-25 21:56:53,627 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346367 is handled. Duration 377 ms by bot id=6638457850
2024-02-25 21:56:54,595 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346368 is handled. Duration 121 ms by bot id=6638457850
2024-02-25 21:56:55,998 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346369 is handled. Duration 191 ms by bot id=6638457850
2024-02-25 21:56:56,657 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346370 is handled. Duration 124 ms by bot id=6638457850
2024-02-25 21:57:06,732 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346371 is handled. Duration 1183 ms by bot id=6638457850
2024-02-25 21:57:11,257 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:57:11,374 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 21:57:11,783 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346372 is handled. Duration 1466 ms by bot id=6638457850
2024-02-25 21:59:41,569 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346373 is handled. Duration 274 ms by bot id=6638457850
2024-02-25 22:00:01,035 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346374 is handled. Duration 254 ms by bot id=6638457850
2024-02-25 22:00:02,320 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346375 is handled. Duration 352 ms by bot id=6638457850
2024-02-25 22:00:03,210 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346376 is handled. Duration 203 ms by bot id=6638457850
2024-02-25 22:00:09,423 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346377 is handled. Duration 167 ms by bot id=6638457850
2024-02-25 22:00:16,377 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:00:16,507 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:00:16,621 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346378 is handled. Duration 2727 ms by bot id=6638457850
2024-02-25 22:01:04,111 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:04,162 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:04,227 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:04,275 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:04,387 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346379 is handled. Duration 634 ms by bot id=6638457850
2024-02-25 22:01:06,512 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-02-25 22:01:59,321 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:59,376 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:59,527 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:59,579 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://postgres:********@localhost/cheat_bot_stu
2024-02-25 22:01:59,776 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346381 is handled. Duration 734 ms by bot id=6638457850
2024-02-25 22:02:03,463 - [INFO] - botocore.credentials - (credentials.py).load(1278) - Found credentials in shared credentials file: ~/.aws/credentials
2024-02-26 18:36:28,092 - [INFO] - databases - (core.py).connect(113) - Connected to database postgres://timurhajrulin:********@localhost/cheat_bot_stu
2024-02-26 18:36:28,285 - [INFO] - databases - (core.py).disconnect(149) - Disconnected from database postgres://timurhajrulin:********@localhost/cheat_bot_stu
2024-02-26 18:36:28,285 - [ERROR] - root - (admin_handlers.py).moderate_image(83) - 'NoneType' object has no attribute 'id'
2024-02-26 18:36:28,749 - [INFO] - aiogram.event - (dispatcher.py).feed_update(172) - Update id=849346522 is handled. Duration 1395 ms by bot id=6638457850
